# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Record' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  pod 'mob_smssdk'
  pod 'AFNetworking'
  pod 'MBProgressHUD'
  pod 'IAPHelper'
  pod 'BmobSDK'
  pod 'MJRefresh'
  pod 'YYKit'
end
